/*
 * generated by Xtext 2.10.0
 */
package eu.esrocos.kul.query


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QueryLangStandaloneSetup extends QueryLangStandaloneSetupGenerated {

	def static void doSetup() {
		new QueryLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
