/*
 * generated by Xtext 2.10.0
 */
package eu.esrocos.kul.robot


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KinDslRuntimeModule extends AbstractKinDslRuntimeModule {
}
